/* generated by mediatek */

package com.gionee.featureoption;

public final class FeatureOption
{
    /**
     * check if GN_FEATURE_PERF_LIST is turned on or not
     */
    public static final boolean GN_FEATURE_PERF_LIST = true;
    /**
     * check if GN_FEATURE_DISPLAY_SENT_TIME is turned on or not
     */
    public static final boolean GN_FEATURE_DISPLAY_SENT_TIME = true;
    /**
     * check if GN_FEATURE_DELETE_RECORD is turned on or not
     */
    public static final boolean GN_FEATURE_DELETE_RECORD = true;
    /**
     * check if GN_FEATURE_INSERT_CONTACT_DRIECTLY is turned on or not
     */
    public static final boolean GN_FEATURE_INSERT_CONTACT_DRIECTLY = true;
    /**
     * check if GN_FEATURE_UNREAD_ICON_CHANGE is turned on or not
     */
    public static final boolean GN_FEATURE_UNREAD_ICON_CHANGE = true;
    /**
     * check if GN_FEATURE_SMART_GUIDE is turned on or not
     */
    public static final boolean GN_FEATURE_SMART_GUIDE = true;
    /**
     * check if GN_FEATURE_PERFOMANCE_OPTIMIZATION_1 is turned on or not
     */
    public static final boolean GN_FEATURE_PERFOMANCE_OPTIMIZATION_1 = true;
    /**
     * check if GN_FEATURE_VOICE_READ_MSG is turned on or not
     */
    public static final boolean GN_FEATURE_VOICE_READ_MSG = true;
    /**
     * check if GN_FEATURE_HIDE_ENCRYPTION is turned on or not
     */
    public static final boolean GN_FEATURE_HIDE_ENCRYPTION = true;
    /**
     * check if GN_FEATURE_PERFOMANCE_OPTIMIZATION_2 is turned on or not
     */
    public static final boolean GN_FEATURE_PERFOMANCE_OPTIMIZATION_2 = true;
    /**
     * check if GN_FEATURE_VOICE_HELPER is turned on or not
     */
    public static final boolean GN_FEATURE_VOICE_HELPER = true;
    /**
     * check if GN_FEATURE_SENSOR_DIAL is turned on or not
     */
    public static final boolean GN_FEATURE_SENSOR_DIAL = true;
    /**
     * check if GN_FEATURE_OPTIMIZE_AUTOCOMPLETE is turned on or not
     */
    public static final boolean GN_FEATURE_OPTIMIZE_AUTOCOMPLETE = true;
    /**
     * check if GN_FEATURE_ALPHBETINDEX is turned on or not
     */
    public static final boolean GN_FEATURE_ALPHBETINDEX = true;
    /**
     * check if GN_FEATURE_ADD_CONTACT is turned on or not
     */
    public static final boolean GN_FEATURE_ADD_CONTACT = true;
    /**
     * check if GN_FEATURE_VOICE_INPUT is turned on or not
     */
    public static final boolean GN_FEATURE_VOICE_INPUT = true;
    /**
     * check if GN_FEATURE_CLOUD_BACKUP is turned on or not
     */
    public static final boolean GN_FEATURE_CLOUD_BACKUP = true;
    /**
     * check if GN_FEATURE_POPUP_NEW is turned on or not
     */
    public static final boolean GN_FEATURE_POPUP_NEW = true;
    /**
     * check if GN_FEATURE_DELETE_DRAF is turned on or not
     */
    public static final boolean GN_FEATURE_DELETE_DRAF = true;
    /**
     * check if GN_FEATURE_PHOTO_STYLE is turned on or not
     */
    public static final boolean GN_FEATURE_PHOTO_STYLE = true;
	public static final boolean MTK_GEMINI_SUPPORT = true;
}
