GN_APK_PLATFORM_VERSION=5.1
GN_APK_PLATFORM_VENDOR=mtk
GN_APK_MTK_PLATFORM=6753
GN_APK_RESOLUTION=hdpi,xhdpi,xxhdpi,xxxhdpi
GN_APK_LANGUAGE=zh_CN,en_US,ru_RU
GN_APK_VERSION=1.0
GN_APP_THEME_SUPPORT=yes
