/* generated by mediatek */

package com.gionee.featureoption;

public final class FeatureOption
{
    public static final boolean GN_FEATURE_PHOTO_STYLE = true;
    public static final boolean GN_FEATURE_SENSOR_DIAL = true;
    public static final boolean GN_FEATURE_DELETE_DRAF = true;
    public static final boolean GN_FEATURE_DISPLAY_SENT_TIME = true;
    public static final boolean GN_FEATURE_ALPHBETINDEX = true;
    public static final boolean GN_FEATURE_CLOUD_BACKUP = true;
    public static final boolean GN_FEATURE_ADD_CONTACT = true;
    public static final boolean GN_FEATURE_VOICE_HELPER = true;
    public static final boolean GN_FEATURE_DELETE_RECORD = true;
    //Gionee <guoyx> <2013-05-03> add for CR00797658 begin
    /**
     *performance optimization for the enterance the Mms app
     */
    public static final boolean GN_FEATURE_PERFOMANCE_OPTIMIZATION_1 = true;

    /**
     *performance optimization for the enterance the Compose Message 
     */
    public static final boolean GN_FEATURE_PERFOMANCE_OPTIMIZATION_2 = true;
    //Gionee <guoyx> <2013-05-03> add for CR00797658 end
    public static final boolean GN_FEATURE_VOICE_INPUT = true;

    //Gionee <gaoj> <2013-05-13> added for CR00811367 begin
    public static final boolean GN_FEATURE_PERF_LIST = true;
    //Gionee <gaoj> <2013-05-13> added for CR00811367 end
    public static final boolean GN_FEATURE_VOICE_READ_MSG = true;

    //Gionee <gaoj> <2013-05-21> added for CR00817770 begin
    public static final boolean GN_FEATURE_HIDE_ENCRYPTION = true;
    //Gionee <gaoj> <2013-05-21> added for CR00817770 end
    public static final boolean GN_FEATURE_OPTIMIZE_AUTOCOMPLETE = true;
    
    //Gionee <guoyx> <2013-05-22> add for CR00818517 begin
    /**
     * new feature add the new number to the contact directly
     */
    public static final boolean GN_FEATURE_INSERT_CONTACT_DRIECTLY = true;
    //Gionee <guoyx> <2013-05-22> add for CR00818517 end

    //Gionee <gaoj> <2013-05-28> add for CR00817770 begin
    public static final boolean GN_FEATURE_SMART_GUIDE = true;
    //Gionee <gaoj> <2013-05-28> add for CR00817770 end
    
    //gionee <gaoj> <2013-07-02> add for CR00832502 begin
    public static final boolean GN_FEATURE_POPUP_NEW = true;
    //gionee <gaoj> <2013-07-02> add for CR00832502 end
    //Gionee <zhouyj> <2013-08-02> add for CR00845643 begin
    public static final boolean GN_FEATURE_UNREAD_ICON_CHANGE = true;
    //Gionee <zhouyj> <2013-08-02> add for CR00845643 end
}
