GN_APK_PLATFORM_VENDOR=mtk
GN_APK_PLATFORM_VERSION=4.2
GN_APK_MTK_PLATFORM=6589
MTK_GEMINI_SUPPORT = yes
GN_APK_RESOLUTION = hdpi,xhdpi,xxhdpi
GN_ZIP_NAME_PALTFORM=6589
GN_ZIP_NAME_ROM=4.2
 GN_APK_VERSION=1.0
