GN_APK_PLATFORM_VERSION = 4.2
GN_APP_THEME_SUPPORT = yes
GN_APK_PLATFORM_VENDOR = mtk
GN_APK_MTK_PLATFORM = 6589
GN_APK_RESOLUTION = ldpi,hdpi,mdpi,nodpi,xhdpi,xxhdpi
GN_APK_LANGUAGE=zh_CN,en_US,ru_RU
GN_APK_VERSION=1.0
