GN_APK_PLATFORM_VERSION=5.0
GN_APK_PLATFORM_VENDOR=mtk
GN_APK_MTK_PLATFORM=6735
GN_APK_VERSION=2.1
#GN_ZIP_NAME_ROM=4.2.3
#GN_APK_LANGUAGE = zh_CN,en_US,ru_RU
GN_APK_RESOLUTION = hdpi,nodpi,xhdpi,xxhdpi,xxxhdpi




