GN_APK_PLATFORM_VERSION=4.2
GN_APK_PLATFORM_VENDOR=mtk
GN_APK_MTK_PLATFORM=6589
GN_APK_RESOLUTION=hdpi,ldpi,mdpi,xhdpi,xxhdpi
                   

GN_RM_PLATFORM=all
GN_RM_MIN_ROM_VERSION=all
GN_RM_MAX_ROM_VERSION=all
GN_RM_MODEL=all
GN_RM_CLIENT_MIN_VERSION=all
GN_RM_CLIENT_MAX_VERSION=all

GN_ZIP_NAME_PLATFORM=6589
GN_ZIP_NAME_ROM=4.2.4
GN_ZIP_NAME_RESOLUTION=hdpi,ldpi,mdpi,xhdpi,xxhdpi
                        
