LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/xbin/amigosu:system/xbin/amigosu

LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := Aurora_PowerSaveLauncher
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)

LOCAL_PRIVILEGED_MODULE := true

include $(BUILD_PREBUILT)

