#!/usr/bin/perl
my $configFile = $ARGV[0];
die "the file $configFile is NOT exsit\n" if ( ! -e $configFile);
open FILE, "<$configFile";
my %config_for;
while (<FILE>) {
	if (/^(\w+)\s*=\s*(\w+)/) {
		$config_for{$1} = $2;
	}
}
close FILE;

my $apk_resource_dir = `dirname $configFile`;
chomp($apk_resource_dir);
my $filedir = "$apk_resource_dir/code/src/com/gionee/featureoption";
my $write_filename = "$filedir/FeatureOption.java";

system("chmod u+w $write_filename") if (-e $write_filename);
system("mkdir -p $filedir") if ( ! -d "$filedir");
die "can NOT open $write_filename:$!" if ( ! open OUT_FILE, ">$write_filename");
print OUT_FILE "\/* generated by mediatek *\/\n\n";
print OUT_FILE "package com.gionee.featureoption;\n";
print OUT_FILE "\npublic final class FeatureOption\n{\n";

foreach $option (keys %config_for){
	if (lc($config_for{$option}) eq "yes") {
		&gen_java_file ($write_filename, $option, "true");
	}
	elsif (lc($config_for{$option}) eq "no"){
		&gen_java_file ($write_filename, $option, "false");
	}
	else
	{
		print "\"$option\" not a java featureoption\n";
	}
}

print OUT_FILE "}\n";
close OUT_FILE;
sub gen_java_file {
	my ($filename, $option, $value) = @_;
	print OUT_FILE "    /**\n     * check if $option is turned on or not\n     */\n";
    print OUT_FILE "    public static final boolean ${option} = $value;\n";
    print "public static final boolean ${option} = $value\n";
}
