/* generated by mediatek */

package com.gionee.featureoption;
import android.os.SystemProperties;

public final class FeatureOption
{
	public static final boolean MTK_GEMINI_SUPPORT = "yes".equals(SystemProperties.get("ro.gn.gemini.support", "yes"));
	public static final boolean MTK_2SDCARD_SWAP = false;
	public static final boolean MTK_DT_SUPPORT = false;
	public static final boolean MTK_THEMEMANAGER_APP = false;
	public static final boolean MTK_WLAN_SUPPORT = true;
	public static final boolean MTK_BT_SUPPORT = true;
	public static final boolean MTK_GPS_SUPPORT = true;
	public static final boolean MTK_AUDIO_PROFILES = true;
	public static final boolean MTK_GEMINI_3G_SWITCH = false;
	public static final boolean MTK_SHARED_SDCARD = false;	
	
	
//Intent start
		public static final String SIM_SETTINGS_INFO_CHANGED = "android.intent.action.SIM_SETTING_INFO_CHANGED";
		
		public static final String ACTION_SKIN_CHANGED = "android.intent.action.SKIN_CHANGED";
//Intent end

//Telephony.Intents start
    public static final String SPN_STRINGS_UPDATED_ACTION =
            "android.provider.Telephony.SPN_STRINGS_UPDATED";

    public static final String SPN_STRINGS_UPDATED_ACTION_SIM1 =
            "android.provider.Telephony.SPN_STRINGS_UPDATED_SIM1";

    public static final String SPN_STRINGS_UPDATED_ACTION_SIM2=
            "android.provider.Telephony.SPN_STRINGS_UPDATED_SIM2";
            
    public static final String EXTRA_SHOW_PLMN  = "showPlmn";
    public static final String EXTRA_PLMN       = "plmn";
    public static final String EXTRA_SHOW_SPN   = "showSpn";
    public static final String EXTRA_SPN        = "spn";
//Telephony.Intents end

//TelephonyIntents start
    public static final String ACTION_SIM_INDICATOR_STATE_CHANGED
    	= "android.intent.action.SIM_INDICATOR_STATE_CHANGED";
    public static final String INTENT_KEY_ICC_SLOT = "slotId";
    public static final String ACTION_SIM_INSERTED_STATUS
        = "android.intent.action.SIM_INSERTED_STATUS";
    public static final String ACTION_SIM_INFO_UPDATE
        = "android.intent.action.SIM_INFO_UPDATE";
//TelephonyIntents end

//Settings.Secure start
    public static final String BATTERY_PERCENTAGE = "battery_percentage";
//Settings.Secure end


//PhoneConstants start
    /**
     * SIM ID for GEMINI
     */
    public static final int GEMINI_SIM_1 = 0;
    public static final int GEMINI_SIM_2 = 1;
    public static final String GEMINI_SIM_ID_KEY = "simId";
    
	  /** UNKNOWN, invalid value */
    public static final int SIM_INDICATOR_UNKNOWN = -1;
    /** ABSENT, no SIM/USIM card inserted for this phone */
    //public static final int SIM_INDICATOR_ABSENT = 0;
    /** RADIOOFF,  has SIM/USIM inserted but not in use . */
    public static final int SIM_INDICATOR_RADIOOFF = 1;
    /** LOCKED,  has SIM/USIM inserted and the SIM/USIM has been locked. */
    public static final int SIM_INDICATOR_LOCKED = 2;
	  /** INVALID : has SIM/USIM inserted and not be locked but failed to register to the network. */
    public static final int SIM_INDICATOR_INVALID = 3; 
	  /** SEARCHING : has SIM/USIM inserted and SIM/USIM state is Ready and is searching for network. */
    public static final int SIM_INDICATOR_SEARCHING = 4; 
	  /** NORMAL = has SIM/USIM inserted and in normal service(not roaming and has no data connection). */
    public static final int SIM_INDICATOR_NORMAL = 5; 
    /** ROAMING : has SIM/USIM inserted and in roaming service(has no data connection). */	
    public static final int SIM_INDICATOR_ROAMING = 6; 
	  /** CONNECTED : has SIM/USIM inserted and in normal service(not roaming) and data connected. */
    public static final int SIM_INDICATOR_CONNECTED = 7; 
	  /** ROAMINGCONNECTED = has SIM/USIM inserted and in roaming service(not roaming) and data connected.*/
    public static final int SIM_INDICATOR_ROAMINGCONNECTED = 8;
	

//PhoneConstants end

//TelephonyProperties start
		public static final String PROPERTY_SIM_INFO_READY = "gsm.siminfo.ready";
//TelephonyProperties end

//ConnectivityManager start
		public static final String EXTRA_SIM_ID = "simId";
//ConnectivityManager end
}
