/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_gallery3d_filtershow_auroraeffects_ImageProcessor */

#ifndef _Included_com_android_gallery3d_filtershow_auroraeffects_ImageProcessor
#define _Included_com_android_gallery3d_filtershow_auroraeffects_ImageProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_gallery3d_filtershow_auroraeffects_ImageProcessor
 * Method:    generateFilteredBitmap
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_android_gallery3d_filtershow_auroraeffects_ImageProcessor_generateFilteredBitmap__Landroid_graphics_Bitmap_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_android_gallery3d_filtershow_auroraeffects_ImageProcessor
 * Method:    generateFilteredBitmap
 * Signature: (Landroid/graphics/Bitmap;I)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_android_gallery3d_filtershow_auroraeffects_ImageProcessor_generateFilteredBitmap__Landroid_graphics_Bitmap_2I
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
