/* generated by mediatek */

package com.gionee.featureoption;

public final class FeatureOption
{
    /**
     * check if GN_FEATUTE_CONTACT_DETAIL is turned on or not
     */
    public static final boolean GN_FEATUTE_CONTACT_DETAIL = true;
    /**
     * check if GN_FEATURE_DIAL_SPEECH_SEARCH is turned on or not
     */
    public static final boolean GN_FEATURE_DIAL_SPEECH_SEARCH = true;
    /**
     * check if GN_FEATURE_AUDIO_SEARCH is turned on or not
     */
    public static final boolean GN_FEATURE_AUDIO_SEARCH = true;
    /**
     * check if GN_FEATURE_QWERT_KEYBOARD_NUMBER is turned on or not
     */
    public static final boolean GN_FEATURE_QWERT_KEYBOARD_NUMBER = true;
    /**
     * check if GN_FEATUTE_TONE_DAILING is turned on or not
     */
    public static final boolean GN_FEATUTE_TONE_DAILING = true;
    /**
     * check if GN_FEATURE_BLUETOOTH_PBAP is turned on or not
     */
    public static final boolean GN_FEATURE_BLUETOOTH_PBAP = true;
    /**
     * check if GN_FEATUTE_CONTACT_EDIT_PHOTO is turned on or not
     */
    public static final boolean GN_FEATUTE_CONTACT_EDIT_PHOTO = true;
    /**
     * check if GN_FEATURE_CALL_LOG_HEADER is turned on or not
     */
    public static final boolean GN_FEATURE_CALL_LOG_HEADER = true;
    /**
     * check if GN_FEATURE_COLORFUL_CONTACT_PHOTO is turned on or not
     */
    public static final boolean GN_FEATURE_COLORFUL_CONTACT_PHOTO = true;
    /**
     * check if GN_FEATURE_SPEED_DIAL is turned on or not
     */
    public static final boolean GN_FEATURE_SPEED_DIAL = true;
    /**
     * check if GN_FEATURE_4_9_0 is turned on or not
     */
    public static final boolean GN_FEATURE_4_9_0 = true;
    /**
     * check if GN_FEATURE_HAND_SENSOR_DIAL is turned on or not
     */
    public static final boolean GN_FEATURE_HAND_SENSOR_DIAL = true;
    /**
     * check if GN_FEATURE_GIONEE_CLOUD_ENTER is turned on or not
     */
    public static final boolean GN_FEATURE_GIONEE_CLOUD_ENTER = true;
    /**
     * check if GN_FEATURE_LISTITEM_ACTION_ALTERABLE is turned on or not
     */
    public static final boolean GN_FEATURE_LISTITEM_ACTION_ALTERABLE = true;
	public static final boolean GN_APP_THEME_SUPPORT = true;
}
