/* generated by mediatek */

package com.gionee.featureoption;

public final class FeatureOption
{
    /**
     * check if MTK_GEMINI_SUPPORT is turned on or not
     */
    public static final boolean MTK_GEMINI_SUPPORT = true;
	public static final boolean GN_APP_THEME_SUPPORT = true;
}
