/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.android.contacts.auroraprivate;

import aurora.preference.AuroraPreferenceActivity;
import aurora.preference.AuroraPreference;
import android.net.Uri;
import android.util.Log;
import android.content.ContentResolver;
import android.provider.ContactsContract;
import android.database.Cursor;
import android.os.Bundle;
import android.content.Intent;
import aurora.widget.AuroraActionBar;
import android.os.Parcelable;

import com.android.contacts.ContactsApplication;
import com.android.contacts.ContactsUtils;
import aurora.preference.AuroraPreferenceScreen;
import android.content.ContentValues;
import com.android.contacts.R;

public class PrivateNotificationSettings extends AuroraPreferenceActivity implements AuroraPreference.OnPreferenceChangeListener {
    private static final boolean DBG = true;
    static final String TAG = "PrivateNotificationSettings";
    private Uri mContactUri;
    private PrivateRadioPreference[] mRadio;
    private long mRawContactId;
    private AuroraPreference[] noti;
    
    
    protected void onCreate(Bundle icicle) {
        super.onCreate(icicle);
        addPreferencesFromResource(R.xml.private_noti_settings);
        String contactName = getIntent().getStringExtra("name");
        getAuroraActionBar().setTitle(contactName);
        Intent intent = getIntent();
        mContactUri = (Uri)intent.getParcelableExtra("contactUri");
        String name = intent.getStringExtra("name");
        getAuroraActionBar().setTitle(name);
        mRawContactId = ContactsUtils.queryForRawContactId(getContentResolver(), Long.parseLong(mContactUri.getLastPathSegment()));
        AuroraPreferenceScreen prefSet = getPreferenceScreen();
        noti = new AuroraPreference[6];
        for(int i = 0; i < 6; i++) {
        	noti[i] = prefSet.findPreference("private_radio_text_" + (i+1));
        	noti[i].setEnabled(false);
        	prefSet.removePreference(noti[i]);
        }
        mRadio = new PrivateRadioPreference[0x2];
        mRadio[0] = (PrivateRadioPreference)prefSet.findPreference("private_radio_2");
        mRadio[1] = (PrivateRadioPreference)prefSet.findPreference("private_radio_1");
        mRadio[0].setOnPreferenceChangeListener(this);
        mRadio[1].setOnPreferenceChangeListener(this);
        int choice = getChoice();
        mRadio[choice].setChecked();
        int base = choice == 0 ? 0 : 3;        
        for(int i = 0; i < 3; i++) {
            prefSet.addPreference(noti[i+base]);
        }
        
	    if (ContactsApplication.sIsAuroraPrivacySupport) {
        	ContactsApplication.mPrivacyActivityList.add(this);
        }
    }
    
    private int getChoice() {
        int result = 0x0;
        Log.i("PrivateNotificationSettings", "getChoice rawContactId = " + mRawContactId);
        Cursor c = getContentResolver().query(ContactsContract.RawContacts.CONTENT_URI, new String[] {"call_notification_type"}, "_id=" + mRawContactId + " and is_privacy > -1", null, null);
        if((c != null) && (c.getCount() > 0)) {
            c.moveToFirst();
            result = c.getInt(0);
        }
        if(c != null) {
            c.close();
        }
        Log.i("PrivateNotificationSettings", "getChoice result = " + result);
        return result;
    }
    
    protected void onResume() {
        super.onResume();
    }
    
    public boolean onPreferenceChange(AuroraPreference preference, Object objValue) {
        Log.d("PrivateNotificationSettings", "onPreferenceChange()");
        AuroraPreferenceScreen prefSet = getPreferenceScreen();
        for(int i = 0; i < 2; i++) {
            if(PrivateRadioPreference.getSelectedKey().equalsIgnoreCase(mRadio[i].getKey())) {
                ContentValues values = new ContentValues();
                values.put("call_notification_type", Integer.valueOf(i));
                getContentResolver().update(ContactsContract.RawContacts.CONTENT_URI, values, "_id=" + mRawContactId + " and is_privacy > -1", null); 
                if(i == 0) {
	                for(int j = 0; j < 3; j++) {
	                    prefSet.addPreference(noti[j]);
	                    prefSet.removePreference(noti[j+3]);
	                }
                } else {
                    for(int j = 0; j < 3; j++) {
	                    prefSet.addPreference(noti[j+3]);
	                    prefSet.removePreference(noti[j]);
	                }
                }
            }
        }
        return true;
    }
    
    private static void log(String msg) {
        Log.d("PrivateNotificationSettings", msg);
    }
    
    protected void onDestroy() {
        super.onDestroy();
        if (ContactsApplication.sIsAuroraPrivacySupport) {
        	ContactsApplication.mPrivacyActivityList.remove(this);
        }
    }
}
