GN_APK_PLATFORM_VERSION = 5.0
# mtk or qcom
GN_APK_PLATFORM_VENDOR = mtk 
# 6589 or 6577
GN_APK_MTK_PLATFORM = 6735
GN_APK_RESOLUTION = ldpi,hdpi,mdpi,nodpi,xhdpi,xxhdpi,xxxhdpi
# GN_APK_LANGUAGE = zh_CN,en_US
GN_APK_VERSION=1.0
